name: longshot
version: 0.1.0.0
synopsis: Fast Brute-force search using parallelism
description: |
  Longshot enables to search for preimages from a given hash value
  using a brute-force method based on parallelism.
  .
  * Support various search lengths, character sets and hashers
  * Strict mode: searches only for a given exact length
  * Deep mode: searches everything less than or equal to a given length.
  * Use @CPUs@ as much as possible. Get the most out of them!
  * Use, however, @memory@ as little as possible.
  .
  Please see the documentation at https://github.com/thyeem/longshot
  for usage example.
  .
category:            algorithm, search, cryptography, parallelism
author:              "Francis Lim, Jongwhan Lee"
copyright:           "Francis, 2020"
maintainer:          "thyeem@gmail.com"
license:             MIT
github:              "thyeem/longshot"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- template-haskell
- bytestring
- parallel
- deepseq
- docopt
- base16-bytestring
- memory
- cryptohash-sha256
- cryptonite
- blake3
- blake2

library:
  source-dirs: src

default-extensions: 
- TemplateHaskell 
- KindSignatures
- DataKinds

executables:
  longshot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    - -feager-blackholing
    - -g0
    - -eventlog
    dependencies:
    - longshot

tests:
  longshot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - longshot
