name:                LongShot
version:             0.1.0.0
github:              "thyeem/LongShot"
license:             MIT
author:              "Francis Lim, Jongwhan Lee"
maintainer:          "thyeem@gmail.com"
copyright:           "Francis, 2020"

extra-source-files:
- README.md

synopsis:            Fast and concise Brute-force search using parallelism
category:            Brute-force method, cryptography, parallelism
description:         Search for preimage from a given hash value using Brute-force method based on parallelism

dependencies:
- base >= 4.7 && < 5
- containers
- template-haskell
- bytestring
- parallel
- deepseq
- docopt
- base16-bytestring
- memory
- cryptohash-sha256
- cryptonite
- blake3
- blake2

library:
  source-dirs: src

default-extensions: 
- TemplateHaskell 
- KindSignatures
- DataKinds

executables:
  longshot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    - -feager-blackholing
    - -g0
    - -eventlog
    dependencies:
    - LongShot 

tests:
  longshot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - LongShot 
